[workspace]
resolver = "2"
members = [
    "router",
    "router/client",
    "launcher"
]
exclude = [
    "server/safetensors",
]

[profile.release]
debug = 1
incremental = true
lto = "off"
#lto = "fat"
#panic = "abort"
