[package]
name = "text-generation-launcher"
version = "0.1.0"
edition = "2021"
authors = ["Olivier Dehaene"]
description = "Text Generation Launcher"

[dependencies]
clap = { version = "4.4.7", features = ["derive", "env"] }
ctrlc = { version = "3.4.1", features = ["termination"] }
subprocess = "0.2.9"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["json"] }

