apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: bloom-

commonLabels:
  app: text-gen-bloom

resources:
  - ../../base

patchesStrategicMerge:
  - ../../base/patches/gpus/8-gpu.yaml
  - ../../base/patches/gpus/a100-80g.yaml
  - ../../base/patches/shm.yaml
  - |-
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: inference-server
   spec:
     replicas: 1
     template:
       spec:
         containers:
           - name: server
             env:
             - name: MODEL_NAME
               value: bigscience/bloom
             - name: DEPLOYMENT_FRAMEWORK
               value: tgis_native
               
             - name: MAX_BATCH_SIZE
               value: "16"
             - name: MAX_CONCURRENT_REQUESTS
               value: "32"
             - name: MAX_SEQUENCE_LENGTH
               value: "4096"
             - name: MAX_NEW_TOKENS
               value: "1536"
