apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-server
spec:
  template:
    spec:
      containers:
        - name: server
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            # Writeable home directory for caches
            - name: home
              mountPath: /home/tgis
            # Need a temp directory for Python
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: home
          emptyDir: {}
        - name: tmp
          emptyDir: {}
