apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-server
spec:
  template:
    metadata:
      labels:
        placement: nvidia-v100
    spec:
      # Colocate small models
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - Tesla-V100-PCIE-16GB
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: placement
                      operator: In
                      values:
                        - nvidia-v100
                topologyKey: kubernetes.io/hostname
