apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml

patchesStrategicMerge:
  - patches/pvcs/pvc.yaml

images:
  - name: text-gen-server
    newName: text-gen-server
    newTag: latest
