apiVersion: v1
kind: Service
metadata:
  name: inference-server
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: inference-server
  ports:
    - name: grpc
      port: 8033
      targetPort: grpc
