apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: flan-t5-3b-

commonLabels:
  app: text-gen-flan-t5-xl

resources:
  - ../../base

patchesStrategicMerge:
  - ../../base/patches/gpus/1-gpu.yaml
  - ../../base/patches/gpus/v100-16g.yaml
  - ../../base/patches/limits/t5-xl-v100.yaml
  - |-
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: inference-server
   spec:
     template:
       spec:
         containers:
           - name: server
             env:
             - name: MODEL_NAME
               value: google/flan-t5-xl
