# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import generation_pb2 as generation__pb2


class GenerationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/fmaas.GenerationService/Generate',
                request_serializer=generation__pb2.BatchedGenerationRequest.SerializeToString,
                response_deserializer=generation__pb2.BatchedGenerationResponse.FromString,
                )
        self.GenerateStream = channel.unary_stream(
                '/fmaas.GenerationService/GenerateStream',
                request_serializer=generation__pb2.SingleGenerationRequest.SerializeToString,
                response_deserializer=generation__pb2.GenerationResponse.FromString,
                )
        self.Tokenize = channel.unary_unary(
                '/fmaas.GenerationService/Tokenize',
                request_serializer=generation__pb2.BatchedTokenizeRequest.SerializeToString,
                response_deserializer=generation__pb2.BatchedTokenizeResponse.FromString,
                )
        self.ModelInfo = channel.unary_unary(
                '/fmaas.GenerationService/ModelInfo',
                request_serializer=generation__pb2.ModelInfoRequest.SerializeToString,
                response_deserializer=generation__pb2.ModelInfoResponse.FromString,
                )


class GenerationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Generate(self, request, context):
        """Generates text given a text prompt, for one or more inputs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateStream(self, request, context):
        """Generates text given a single input prompt, streaming the response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tokenize(self, request, context):
        """Tokenize text
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModelInfo(self, request, context):
        """Model info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenerationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=generation__pb2.BatchedGenerationRequest.FromString,
                    response_serializer=generation__pb2.BatchedGenerationResponse.SerializeToString,
            ),
            'GenerateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateStream,
                    request_deserializer=generation__pb2.SingleGenerationRequest.FromString,
                    response_serializer=generation__pb2.GenerationResponse.SerializeToString,
            ),
            'Tokenize': grpc.unary_unary_rpc_method_handler(
                    servicer.Tokenize,
                    request_deserializer=generation__pb2.BatchedTokenizeRequest.FromString,
                    response_serializer=generation__pb2.BatchedTokenizeResponse.SerializeToString,
            ),
            'ModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.ModelInfo,
                    request_deserializer=generation__pb2.ModelInfoRequest.FromString,
                    response_serializer=generation__pb2.ModelInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fmaas.GenerationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GenerationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fmaas.GenerationService/Generate',
            generation__pb2.BatchedGenerationRequest.SerializeToString,
            generation__pb2.BatchedGenerationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/fmaas.GenerationService/GenerateStream',
            generation__pb2.SingleGenerationRequest.SerializeToString,
            generation__pb2.GenerationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Tokenize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fmaas.GenerationService/Tokenize',
            generation__pb2.BatchedTokenizeRequest.SerializeToString,
            generation__pb2.BatchedTokenizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fmaas.GenerationService/ModelInfo',
            generation__pb2.ModelInfoRequest.SerializeToString,
            generation__pb2.ModelInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
