apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: mt0-

commonLabels:
  app: text-gen-mt0-xxl

resources:
  - ../../base

patchesStrategicMerge:
  - ../../base/patches/gpus/1-gpu.yaml
  - ../../base/patches/gpus/a100-80g.yaml
  - ../../base/patches/limits/t5-xxl.yaml
  - |-
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: inference-server
   spec:
     template:
       spec:
         containers:
           - name: server
             env:
             - name: MODEL_NAME
               value: bigscience/mt0-xxl
             - name: MAX_BATCH_WEIGHT
               value: "44752800"
