apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: mpt-7b-

commonLabels:
  app: text-gen-mpt-7b

resources:
  - ../../base

patchesStrategicMerge:
  - ../../base/patches/gpus/1-gpu.yaml
  - ../../base/patches/gpus/a100-80g.yaml
  - |-
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: inference-server
   spec:
     template:
       spec:
         containers:
           - name: server
             env:
             - name: MODEL_NAME
               value: mosaicml/mpt-7b
             - name: TRUST_REMOTE_CODE
               value: "true"
             - name: MAX_SEQUENCE_LENGTH
               value: "2048"
             #- name: OUTPUT_SPECIAL_TOKENS
             #  value: "true"

             - name: MAX_BATCH_SIZE
               value: "64"
             - name: MAX_CONCURRENT_REQUESTS
               value: "100"
             - name: MAX_NEW_TOKENS
               value: "1024"
             - name: MAX_PREFILL_WEIGHT
               value: "2000000"
             - name: MAX_BATCH_WEIGHT
               value: "200000000"
