apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: mpt-7b-

commonLabels:
  app: text-gen-mpt-7b

resources:
  - ../../base

patchesStrategicMerge:
  - ../../base/patches/gpus/1-gpu.yaml
  - ../../base/patches/gpus/a100-80g.yaml
  - |-
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: inference-server
   spec:
     template:
       spec:
         containers:
           - name: server
             env:
             - name: MODEL_NAME
               value: mosaicml/mpt-7b
             - name: TRUST_REMOTE_CODE
               value: "true"
             - name: MAX_SEQUENCE_LENGTH
               value: "2048"
             - name: DEPLOYMENT_FRAMEWORK
               value: "hf_transformers"
             #- name: OUTPUT_SPECIAL_TOKENS
             #  value: "true"


             startupProbe:
               httpGet:
                 port: http
                 path: /health
               # MPT-7B currently takes more than 20 mins to load :-(
               failureThreshold: 52
               periodSeconds: 30