name: "Build"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "build_cache"
    paths-ignore:
      - "**.md"
      - "proto/**"
  pull_request:
    branches:
      - "main"
      - "build_cache"
    paths-ignore:
      - "**.md"
      - "proto/**"

defaults:
  run:
    shell: bash

env:
  CI: true
  SERVER_IMAGE_NAME: "text-gen-server:0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Free up disk space"
      uses: ./.github/actions/free-up-disk-space

    - name: "Set up QEMU"
      uses: docker/setup-qemu-action@v3

    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v3
      with:
        config-inline: |
          [worker.oci]
            max-parallelism = 2

    - name: "Check disk usage"
      shell: bash
      run: |
        docker system df
        df -h

    - name: "Docker build python-builder"
      uses: docker/build-push-action@v5
      with:
        context: .
        target: python-builder
        tags: python-builder
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: "Check disk usage"
      shell: bash
      run: |
        docker system df
        df -h

    - name: "Docker build flash-att-builder"
      uses: docker/build-push-action@v5
      with:
        context: .
        target: flash-att-builder
        tags: flash-att-builder
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: "Check disk usage"
      shell: bash
      run: |
        docker system df
        df -h

    - name: "Docker build flash-att-v2-builder"
      uses: docker/build-push-action@v5
      with:
        context: .
        target: flash-att-v2-builder
        tags: flash-att-v2-builder
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: "Check disk usage"
      shell: bash
      run: |
        docker system df
        df -h

    - name: "Docker build auto-gptq-installer"
      uses: docker/build-push-action@v5
      with:
        context: .
        target: auto-gptq-installer
        tags: auto-gptq-installer
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: "Check disk usage"
      shell: bash
      run: |
        docker system df
        df -h

    - name: "Docker build router-builder"
      uses: docker/build-push-action@v5
      with:
        context: .
        target: router-builder
        tags: router-builder
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: "Check disk usage"
      shell: bash
      run: |
        docker system df
        df -h

    - name: "Docker build server-release"
      uses: docker/build-push-action@v5
      with:
        context: .
        target: server-release
        tags: server-release
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true

    - name: "List docker images"
      run: docker images

    - name: "Check disk usage"
      shell: bash
      run: |
        docker system df
        df -h
