name: "Build"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - "proto/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      DOCKER_BUILDKIT: 1

    steps:
      - name: "Free up disk space"
        uses: ./.github/actions/free-up-disk-space

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v2

      - name: "Build server release"
        run: make build
