name: "Build"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "build_cache"
    paths-ignore:
      - "**.md"
      - "proto/**"
  pull_request:
    branches:
      - "main"
      - "build_cache"
    paths-ignore:
      - "**.md"
      - "proto/**"

defaults:
  run:
    shell: bash

env:
  CI: true
  SERVER_IMAGE_NAME: "text-gen-server:0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Free up disk space"
      uses: ./.github/actions/free-up-disk-space

    - name: "Set up QEMU"
      uses: docker/setup-qemu-action@v3

    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v3

    - name: "Docker build server-release"
      uses: docker/build-push-action@v5
      with:
        context: .
        target: server-release
        tags: server-release
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true

    - name: "List docker images"
      run: docker images

    - name: "Check disk usage"
      shell: bash
      run: |
        docker system df
        df -h
