name: "Test"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "proto/**"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
      DOCKER_BUILDKIT: 1

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Free up disk space"
      uses: ./.github/actions/free-up-disk-space

    - name: "Setup Docker Buildx"
      uses: docker/setup-buildx-action@v2

    - name: "Build test image"
      run: make build-test-image

    - name: "Run Python tests"
      run: make python-tests

    - name: "Run integration tests"
      run: make integration-tests
