name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
#      - '.github/**'
      - '**.md'
      - 'proto/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
      DOCKER_BUILDKIT: 1

    steps:
    - name: "Free up disk space"
      shell: bash
      run: |
        # https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
        echo "Disk usage before cleanup:"
        df -h
        echo "Removing non-essential tools and libraries ..."
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/share/boost
        echo "Deleting libraries for Android (12G), CodeQL (5.3G), PowerShell (1.3G), Swift (1.7G) ..."
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf "${AGENT_TOOLSDIRECTORY}/CodeQL"
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/share/swift
        echo "Disk usage after cleanup:"
        df -h

    - name: "Prune docker images"
      shell: bash
      run: |
        echo "Pruning docker images ..."
        docker image prune -a -f
        docker system df
        echo "Disk usage after pruning docker images:"
        df -h

    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Setup Docker Buildx"
      uses: docker/setup-buildx-action@v2

    - name: "Build"
      run: make build

    - name: "Build test-image"
      run: make build-test-image

    - name: "Python tests"
      run: make python-tests

    - name: "Integration tests"
      run: make integration-tests
